### ISSUE TITLE
is it work in champion select too ?

### ISSUE THREAD

**Issue by gilad207** [pinguluk/League-Of-Legends-Runes-Reforged-Changer#1]
i want to dynamicly change runes every game

**Comment by pinguluk** [comment]
Hi, firstly, I said that this project has been discontinued, due the lack of time.
Secondly, yes, it used to work dynamically in champion select as well.
I'm sorry but you'll have to find another alternative for now :(

**Comment by gilad207** [comment]
why alternative? it work properly isn't it?

**Comment by pinguluk** [comment]
No, it doesn't work properly anymore, because they added new runes
